from pydantic import BaseModel, Field  # used for data validation and serialization
from typing import Optional            # Allows for optional fields in Pydantic models
from datetime import datetime          # used to track time
import uuid                            # used to generate unique task IDs


# this model define what input the user must provide to start a research task, including the research query and an optional limit on subtopics
class ResearchRequest(BaseModel):

    # 'query' is required (...) and must be atleast 5 character long. It represents the research topic or question that the user wants to explore.
    query: str = Field(..., min_length=5, description="Research topic or question") 
    
    # Optional field to control how many subtopics the agent should explore. It must be between 1 and 6 if provided.
    max_subtopics: Optional[int] = Field(None, ge=1, le=6)


# it is used to store logs from each AI agent steps, including which agent is speaking, the message content, and a timestamp for when the message was generated.
class AgentLog(BaseModel):
    agent: str                         # name of agent (e.g., "Researcher", "Planner", "Writer")
    message: str                       # what the agent said or did
    timestamp: str                     # when the message was generated (ISO format)


# this model represents the full lifecycle of a research task, including its unique ID, the original query, current status, the plan generated by the agent, logs of interactions, final report, citations, revision count, and timestamps for creation and completion. It also includes an optional error field to capture any issues that arise during processing.
class TaskStatus(BaseModel):
    task_id: str
    query: str
    status: str           # pending | running | completed | failed
    plan: list[str]
    logs: list[AgentLog]
    report: Optional[str]
    citations: list[str]
    revision_count: int
    created_at: str
    completed_at: Optional[str]
    error: Optional[str]

# this fun create new task with default values for all fields except the query, which is provided by the user. It generates a unique task ID using uuid4, sets the status to "pending", initializes empty lists for the plan, logs, and citations, and sets the revision count to 0. The created_at timestamp is set to the current time in ISO format, while completed_at and error are initialized as None.
def new_task(query: str) -> TaskStatus:
    return TaskStatus(
        task_id=str(uuid.uuid4())[:8],
        query=query,
        status="pending",
        plan=[],
        logs=[],
        report=None,
        citations=[],
        revision_count=0,
        created_at=datetime.utcnow().isoformat(),
        completed_at=None,
        error=None,
    )